"""Add asset management fields

Revision ID: 363bc6815b87
Revises: f3e4524249ce
Create Date: 2026-07-26 18:50:58.816990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363bc6815b87'
down_revision: Union[str, Sequence[str], None] = 'f3e4524249ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_type', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('environment', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('status', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'last_seen')
    op.drop_column('assets', 'status')
    op.drop_column('assets', 'environment')
    op.drop_column('assets', 'owner')
    op.drop_column('assets', 'asset_type')
    # ### end Alembic commands ###
