"""create security events table

Revision ID: 42cacdaf2435
Revises: 299c55b28de5
Create Date: 2026-07-26 21:16:16.411784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42cacdaf2435'
down_revision: Union[str, Sequence[str], None] = '299c55b28de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('raw_event', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('destination_ip', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
