"""Add threat hunting reports table

Revision ID: 8eb7b3bd8f70
Revises: 1ce2e96cf5d8
Create Date: 2026-08-02 13:52:25.431460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb7b3bd8f70'
down_revision: Union[str, Sequence[str], None] = '1ce2e96cf5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_hunting_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=255), nullable=True),
    sa.Column('mitre', sa.String(length=100), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_hunting_reports_id'), 'threat_hunting_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_hunting_reports_id'), table_name='threat_hunting_reports')
    op.drop_table('threat_hunting_reports')
    # ### end Alembic commands ###
