"""create mitre mappings table

Revision ID: bf03d468fb6f
Revises: 6c462b53c1c2
Create Date: 2026-07-26 22:52:29.056914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf03d468fb6f'
down_revision: Union[str, Sequence[str], None] = '6c462b53c1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('technique_name', sa.String(length=255), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_mappings_id'), 'mitre_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitre_mappings_id'), table_name='mitre_mappings')
    op.drop_table('mitre_mappings')
    # ### end Alembic commands ###
